public class Plan {

    /*

    [] BASIC SYNTAX
    [] DATA TYPES
    [] VARIABLES
    [] CONSTANTS
    [] CONDITIONALS
    [] FUNCTIONS
    [] LOOPS
    [] EXCEPTION HANDLING
    [] DATA STRUCTURES
    [] OOP
    [] INTERFACES
    [] CLASSES
    [] METHODS
    [] POINTERS
    [] PACKAGES
    [] COLLECTION FRAMEWORK
    [] STREAMS
    [] GENERICS
    [] ARRAY
    [] ARRAY LIST
    [] SERIALIZATION
    [] MEMORY MANAGEMENT
    [] ROUTINES
    [] THREADS
    [] WORKING WITH FILES & SOCKETS
    [] GARBAGE COLLECTION
    [] HOW JVM WORKS?


    **/



}
